---
-
  become: true
  become_method: sudo
  become_user: root
  hosts: "{{ servers }}"
  tasks:
    - name: "yum clean"
      command: "/usr/bin/yum clean all"

    - name: Apply Security Updates from RHEL Repos, exclude kernel
      yum:
        name: '*'
        state: latest
        exclude: kernel*
        security: yes
        update_cache: yes
        disablerepo: "*"
        enablerepo: "rhel*,clone*"

    - name: "Prevent fsck"
      file:
        path: "/fastboot"
        state: touch

    - name: "Restart server"
      reboot:

    - name: "Update VMtools"
      command: "/usr/bin/vmware-config-tools.pl -d"
      when: ansible_distribution_major_version == "6" and tools_exist.stat.exists
