---
-
  become: true
  become_method: sudo
  become_user: root
  hosts: "{{ servers }}"
  tasks:
    - name: "yum clean"
      command: "/usr/bin/yum clean all"

    - name: Check that the VM Tools exist
      stat:
        path: /usr/bin/vmware-uninstall-tools.pl
      register: tools_exist

    - name: removing vmware tools if a vm and RHEL7/8
      command: /usr/bin/vmware-uninstall-tools.pl
      when: ansible_os_family == "RedHat" and ansible_virtualization_type == "VMware" and ansible_distribution_major_version != "6" and tools_exist.stat.exists

    - name: installing open-vm-tools
      yum: name=open-vm-tools
         state=present
      when: ansible_os_family == "RedHat" and ansible_virtualization_type == "VMware" and ansible_distribution_major_version != "6"

    - name: starting and enabling open-vm-tools
      service: name=vmtoolsd.service state=restarted enabled=yes
      when: ansible_os_family == "RedHat" and ansible_virtualization_type == "VMware" and ansible_distribution_major_version != "6"

    - name: Apply Security Updates from RHEL Repos, exclude kernel
      yum:
        name: '*'
        state: latest
        exclude: kernel*
        security: yes
        update_cache: yes
        disablerepo: "*"
        enablerepo: "rhel*,clone*"
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version != "8"

    - name: Apply Security Updates from RHEL Repos, exclude kernel -- RHEL8
      dnf:
        name: '*'
        state: latest
        exclude: kernel*
        security: yes
        update_cache: yes
        disablerepo: "*"
        enablerepo: "rhel*,clone*"
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"


    - name: "Prevent fsck"
      file:
        path: "/fastboot"
        state: touch

    - name: "Restart server"
      reboot:

    - name: "Update VMtools"
      command: "/usr/bin/vmware-config-tools.pl -d"
      when: ansible_distribution_major_version == "6" and tools_exist.stat.exists
